Repository peiva-git/SDM_project, pull requests merged in 2023-04, with the labels that each got.

#60 Refactoring `MapBoard` references
  src/main/java/it/units/sdm/project/core/FreedomPointsCounter.java
  src/main/java/it/units/sdm/project/core/MapBoard.java
  src/main/java/it/units/sdm/project/interfaces/Board.java
  src/test/java/FreedomPointsCounterTests.java
Labels: enhancement

#62 Set up the libGDX project
  assets/badlogic.jpg
  build.gradle
  core/build.gradle
  core/src/it/units/sdm/project/Freedom.java
  core/src/it/units/sdm/project/Player.java
  core/src/it/units/sdm/project/Position.java
  core/src/it/units/sdm/project/Stone.java
  core/src/it/units/sdm/project/TextInput.java
  core/src/it/units/sdm/project/core/FreedomGame.java
  core/src/it/units/sdm/project/core/FreedomLine.java
  core/src/it/units/sdm/project/core/FreedomPointsCounter.java
  core/src/it/units/sdm/project/core/MapBoard.java
  core/src/it/units/sdm/project/exceptions/InvalidBoardSizeException.java
  core/src/it/units/sdm/project/exceptions/InvalidPositionException.java
  core/src/it/units/sdm/project/interfaces/Board.java
  core/src/it/units/sdm/project/interfaces/Game.java
  core/src/it/units/sdm/project/interfaces/UserInput.java
  core/src/it/units/sdm/project/utils/MainLogger.java
  core/test/java/FreedomLineTests.java
  core/test/java/FreedomPointsCounterTests.java
  core/test/java/MapBoardTests.java
  core/test/java/PlayerTests.java
  core/test/java/PositionTests.java
  core/test/java/StoneTests.java
  desktop/build.gradle
  desktop/src/it/units/sdm/project/DesktopLauncher.java
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/it/units/sdm/project/Main.java
  src/test/java/MainTests.java
Labels: enhancement

#65 Added web application setup
  .circleci/config.yml
  .gitignore
  build.gradle
  core/build.gradle
  core/src/FreedomGame.gwt.xml
  core/src/it/units/sdm/project/core/board/MapBoard.java
  core/src/it/units/sdm/project/core/board/Position.java
  core/src/it/units/sdm/project/core/board/Stone.java
  core/src/it/units/sdm/project/core/game/FreedomLine.java
  core/src/it/units/sdm/project/core/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/core/game/Player.java
  core/src/it/units/sdm/project/core/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/interfaces/Board.java
  core/src/it/units/sdm/project/interfaces/Game.java
  core/src/it/units/sdm/project/interfaces/UserInput.java
  core/test/java/FreedomLineTests.java
  core/test/java/FreedomPointsCounterTests.java
  core/test/java/MapBoardTests.java
  core/test/java/PlayerTests.java
  core/test/java/PositionTests.java
  core/test/java/StoneTests.java
  desktop/build.gradle
  desktop/src/it/units/sdm/project/DesktopLauncher.java
  html/build.gradle
  html/src/it/units/sdm/project/GdxDefinition.gwt.xml
  html/src/it/units/sdm/project/GdxDefinitionSuperdev.gwt.xml
  html/src/it/units/sdm/project/client/HtmlLauncher.java
  html/webapp/WEB-INF/web.xml
  html/webapp/index.html
  html/webapp/styles.css
  settings.gradle
  terminal/.gitignore
  terminal/build.gradle
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
  terminal/src/main/java/it/units/sdm/project/TextInput.java
Labels: enhancement

#68 Updated README.md with modules' information
  README.md
Labels: documentation, enhancement

#73 Logging
  core/src/it/units/sdm/project/core/board/MapBoard.java
  core/src/it/units/sdm/project/utils/MainLogger.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: bug

#74 Refactored `MapBoard` class
  core/src/it/units/sdm/project/core/board/MapBoard.java
  core/src/it/units/sdm/project/interfaces/Board.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: enhancement

#76 Removed `Board` iterator
  core/src/it/units/sdm/project/core/board/MapBoard.java
  core/src/it/units/sdm/project/interfaces/Board.java
  core/test/java/MapBoardTests.java
Labels: enhancement

#78 Tests and general refactoring
  core/src/it/units/sdm/project/core/game/FreedomLine.java
  core/src/it/units/sdm/project/interfaces/Game.java
  core/src/it/units/sdm/project/interfaces/UserInput.java
  core/test/java/FreedomPointsCounterTests.java
  core/test/java/MapBoardTests.java
  core/test/java/PositionTests.java
  core/test/java/providers/FreedomPointsCounterProviders.java
  core/test/java/providers/MapBoardProviders.java
  core/test/java/providers/PositionProviders.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TextInput.java
Labels: enhancement
