Repository peiva-git/SDM_project, pull requests merged in 2023-06, with the labels that each got.

#107 Refactored `TileClickListener`
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/FreedomBoardHelper.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/enums/Direction.java
  core/src/it/units/sdm/project/enums/GameStatus.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomBoardStatusObserver.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/GameScreen.java
  core/src/it/units/sdm/project/game/gui/GameStatusChangeDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
  core/test/java/FreedomHelperTests.java
  core/test/java/MapBoardTests.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: enhancement

#111 Basic texture pack usage implemented
  assets/UI/default.fnt
  assets/UI/uiskin.atlas
  assets/UI/uiskin.json
  assets/UI/uiskin.png
  assets/circle2.png
  assets/freedom.atlas
  assets/freedom.png
  assets/freedom_logo.png
  assets/redCircle.png
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
Labels: enhancement

#112 Added `FreedomBoardStatusObserver` to the `terminal` module
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: enhancement

#116 Added dialog padding
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
Labels: enhancement

#114 Added documentation
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Position.java
  core/src/it/units/sdm/project/board/Stone.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/board/gui/package-info.java
  core/src/it/units/sdm/project/board/package-info.java
  core/src/it/units/sdm/project/exceptions/InvalidBoardSizeException.java
  core/src/it/units/sdm/project/exceptions/InvalidPositionException.java
  core/src/it/units/sdm/project/exceptions/package-info.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomBoardStatusObserver.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/Move.java
  core/src/it/units/sdm/project/game/Player.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/package-info.java
  core/src/it/units/sdm/project/game/gui/package-info.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
  core/src/it/units/sdm/project/game/gui/screens/package-info.java
  core/src/it/units/sdm/project/game/package-info.java
  core/test/java/PlayerTests.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalInputReader.java
Labels: documentation

#129 Refactored FreedomGame
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: enhancement

#131 Updated README.md
  README.md
Labels: documentation

#130 Added `CellHighlighter` class
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
Labels: enhancement

#132 Color restriction
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/Player.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: enhancement

#133 `MainMenuScreen` input listener
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
Labels: enhancement

#136 Create publish-webapp.yml
  .github/workflows/publish-webapp.yml
Labels: enhancement, help wanted

#137 Game deployed online!
  .github/workflows/deploy-webapp.yml
  README.md
  html/webapp/index.html
  html/webapp/styles.css
Labels: enhancement

#135 Removed magic numbers
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Position.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
  core/test/java/providers/PositionProviders.java
Labels: enhancement

#138 Documentation refactoring
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Position.java
  core/src/it/units/sdm/project/board/Stone.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomBoardStatusObserver.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/Move.java
  core/src/it/units/sdm/project/game/Player.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
  terminal/src/main/java/it/units/sdm/project/BoardSizeValidator.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/NameSizeValidator.java
  terminal/src/main/java/it/units/sdm/project/TerminalInputReader.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: documentation

#139 Introduced input form
  assets/UI/default.fnt
  assets/UI/uiskin.atlas
  assets/UI/uiskin.json
  assets/UI/uiskin.png
  build.gradle
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/screens/FormLayout.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/MainMenuScreen.java
  core/src/it/units/sdm/project/game/gui/screens/PlayersNamesFormScreen.java
  html/src/it/units/sdm/project/GdxDefinition.gwt.xml
  html/src/it/units/sdm/project/GdxDefinitionSuperdev.gwt.xml
  terminal/src/main/java/it/units/sdm/project/TerminalInputReader.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: enhancement

#141 Added Android support
  .circleci/config.yml
  android/AndroidManifest.xml
  android/build.gradle
  android/ic_launcher-web.png
  android/proguard-rules.pro
  android/project.properties
  android/res/drawable-anydpi-v26/ic_launcher.xml
  android/res/drawable-anydpi-v26/ic_launcher_foreground.xml
  android/res/drawable-hdpi/ic_launcher.png
  android/res/drawable-mdpi/ic_launcher.png
  android/res/drawable-xhdpi/ic_launcher.png
  android/res/drawable-xxhdpi/ic_launcher.png
  android/res/drawable-xxxhdpi/ic_launcher.png
  android/res/values-v21/styles.xml
  android/res/values/color.xml
  android/res/values/strings.xml
  android/res/values/styles.xml
  android/src/it/units/sdm/project/AndroidLauncher.java
  build.gradle
  desktop/build.gradle
  html/build.gradle
  settings.gradle
Labels: enhancement

#143 Added docs
  android/build.gradle
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/screens/FormLayout.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/PlayersNamesFormScreen.java
  core/src/it/units/sdm/project/game/gui/screens/SplashScreen.java
Labels: documentation

#146 Added android release build to `config.yml`
  .circleci/config.yml
Labels: enhancement

#147 Added Libgdx testing
  build.gradle
  core/build.gradle
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/test/java/board/BoardTests.java
  core/test/java/board/MapBoardTests.java
  core/test/java/board/PositionTests.java
  core/test/java/board/StoneTests.java
  core/test/java/board/gui/providers/PositionProviders.java
  core/test/java/board/providers/MapBoardProviders.java
  core/test/java/board/providers/PositionProviders.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/game/PlayerTests.java
  core/test/java/game/gui/CellHighlighterTests.java
  core/test/java/game/providers/FreedomLineProviders.java
  core/test/java/game/providers/FreedomPointsCounterProviders.java
  core/test/java/utility/BoardUtils.java
  core/test/java/utility/FreedomHeadlessApplicationUtils.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: documentation, enhancement

#151 144 general refactoring
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Position.java
  core/src/it/units/sdm/project/board/Stone.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/Move.java
  core/src/it/units/sdm/project/game/Player.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/src/it/units/sdm/project/game/gui/dialogs/LastMoveDialog.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/PlayersNamesFormScreen.java
  core/src/it/units/sdm/project/game/gui/screens/SplashScreen.java
  core/test/java/board/BoardTests.java
  core/test/java/board/MapBoardTests.java
  core/test/java/board/PositionTests.java
  core/test/java/board/StoneTests.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/game/PlayerTests.java
  core/test/java/game/gui/CellHighlighterTests.java
  html/src/it/units/sdm/project/client/HtmlLauncher.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalInputReader.java
Labels: enhancement

#161 Introduced the `Piece` interface
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Piece.java
  core/src/it/units/sdm/project/board/Stone.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomBoardStatusObserver.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/Player.java
  core/src/it/units/sdm/project/game/gui/FreedomCellHighlighter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/test/java/board/BoardTests.java
  core/test/java/board/MapBoardTests.java
  core/test/java/board/StoneTests.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/utility/BoardUtils.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: enhancement

#169 Added suggested attribute
  android/AndroidManifest.xml
Labels: enhancement

#166 Bug corrected
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
Labels: bug

#164 Expanded and refactored tests for the `it.units.sdm.project.board` package
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/test/java/board/BoardTests.java
  core/test/java/board/MapBoardTests.java
  core/test/java/board/PositionTests.java
  core/test/java/board/StoneTests.java
  core/test/java/board/gui/GuiBoardTests.java
  core/test/java/board/gui/GuiStoneTests.java
  core/test/java/board/gui/providers/GuiBoardProviders.java
  core/test/java/board/gui/providers/GuiStoneProviders.java
  core/test/java/board/gui/providers/PositionProviders.java
  core/test/java/board/providers/BoardProviders.java
  core/test/java/board/providers/PieceProviders.java
  core/test/java/board/providers/PositionProviders.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/utility/BoardUtils.java
  terminal/src/main/java/it/units/sdm/project/BoardSizeValidator.java
Labels: documentation, enhancement

#170 163 game tests
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/game/MoveTests.java
  core/test/java/game/PlayerTests.java
  core/test/java/game/gui/CellHighlighterTests.java
  core/test/java/game/providers/CellHighlighterProviders.java
  core/test/java/game/providers/FreedomPointsCounterProviders.java
  core/test/java/game/providers/MoveProviders.java
  core/test/java/game/providers/PlayerProviders.java
Labels: documentation, enhancement

#172 Implemented single boardSize field
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/screens/GameScreen.java
  core/src/it/units/sdm/project/game/gui/screens/PlayersNamesFormScreen.java
  core/test/java/board/BoardTests.java
  core/test/java/board/MapBoardTests.java
  core/test/java/board/gui/GuiBoardTests.java
  core/test/java/board/providers/BoardProviders.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/FreedomPointsCounterTests.java
  core/test/java/game/gui/CellHighlighterTests.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: bug, documentation, enhancement

#176 175 freedomstatusobserver test coverage
  core/src/it/units/sdm/project/game/FreedomBoardStatusObserver.java
  core/src/it/units/sdm/project/game/gui/dialogs/GameOverDialog.java
  core/test/java/game/FreedomBoardStatusObserverTests.java
  core/test/java/game/providers/FreedomBoardStatusObserverProvider.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
Labels: enhancement

#178 `TileClickListener` refactoring
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
Labels: enhancement

#177 Refactoring `GuiBoard`
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
Labels: enhancement

#174 171 freedomline test coverage
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/test/java/game/FreedomLineTests.java
  core/test/java/game/providers/FreedomLineProviders.java
Labels: enhancement

#180 Added equals Position tests
  core/test/java/board/PositionTests.java
  core/test/java/board/providers/PositionProviders.java
Labels: duplicate, enhancement

#181 Refactored `toString()` method
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Stone.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/test/java/board/StoneTests.java
  core/test/java/game/FreedomLineTests.java
Labels: enhancement

#184 Added terminal validation tests
  build.gradle
  terminal/src/main/java/it/units/sdm/project/NameSizeValidator.java
  terminal/test/java/BoardSizeValidationTests.java
  terminal/test/java/NameSizeValidationTests.java
Labels: enhancement

#185 Added GUI form validation tests
  core/src/it/units/sdm/project/game/gui/screens/FormLayout.java
  core/test/java/game/gui/FormValidationTests.java
Labels: enhancement

#187 Last refactoring
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/gui/TileClickListener.java
  core/src/it/units/sdm/project/game/BoardGame.java
  core/src/it/units/sdm/project/game/FreedomLine.java
Labels: documentation, enhancement
