Repository peiva-git/SDM_project, pull requests merged in 2023-05, with the labels that each got.

#80 Create LICENSE.md
  LICENSE.md
Labels: documentation, enhancement

#82 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#88 Now saving test results to CircleCI
  .circleci/config.yml
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
  terminal/src/main/java/it/units/sdm/project/TextInput.java
Labels: enhancement

#89 Suggested refactoring and debugging
  core/src/it/units/sdm/project/board/Board.java
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/board/Position.java
  core/src/it/units/sdm/project/board/gui/GuiBoard.java
  core/src/it/units/sdm/project/board/gui/GuiStone.java
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/FreedomPointsCounter.java
  core/src/it/units/sdm/project/game/gui/FreedomGame.java
  core/src/it/units/sdm/project/game/gui/GameScreen.java
  core/src/it/units/sdm/project/game/gui/MainMenuScreen.java
  core/src/it/units/sdm/project/game/gui/TiledMapActor.java
  core/test/java/FreedomLineTests.java
  core/test/java/FreedomPointsCounterTests.java
  core/test/java/MapBoardTests.java
  core/test/java/PositionTests.java
  core/test/java/providers/FreedomLineProviders.java
  core/test/java/providers/MapBoardProviders.java
  core/test/java/providers/PositionProviders.java
  core/test/java/utility/TestUtilities.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
Labels: bug, duplicate, enhancement

#91 Added input parameters for the terminal version with validation
  .circleci/config.yml
  build.gradle
  core/src/it/units/sdm/project/board/MapBoard.java
  core/src/it/units/sdm/project/game/gui/TiledMapActor.java
  terminal/build.gradle
  terminal/src/main/java/it/units/sdm/project/BoardSizeValidator.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/NameSizeValidator.java
  terminal/src/main/java/it/units/sdm/project/TerminalLauncher.java
  terminal/src/main/java/it/units/sdm/project/TextInput.java
Labels: bug, enhancement

#94 Main menu
  assets/freedom_logo.png
  assets/skin/default.fnt
  assets/skin/uiskin.atlas
  assets/skin/uiskin.json
  assets/skin/uiskin.png
  core/src/it/units/sdm/project/game/FreedomLine.java
  core/src/it/units/sdm/project/game/gui/MainMenuScreen.java
Labels: enhancement

#98 Bug corrected
  core/src/it/units/sdm/project/board/MapBoard.java
  core/test/java/providers/MapBoardProviders.java
  terminal/src/main/java/it/units/sdm/project/BoardSizeValidator.java
  terminal/src/main/java/it/units/sdm/project/FreedomGame.java
  terminal/src/main/java/it/units/sdm/project/TerminalInputReader.java
Labels: bug, enhancement
