Repository peiva-git/SDM_project, pull requests merged in 2023-03, with the labels that each got.

#7 Updated class_diagram.drawio
  class_diagram.drawio
Labels: documentation

#13 Added Color class
  src/main/java/Color.java
Labels: enhancement

#15 Added Position class
  build.gradle
  src/main/java/Position.java
  src/main/java/exceptions/InvalidPositionException.java
  src/test/java/PositionTests.java
Labels: enhancement

#16 First implementation of the Cell class
  src/main/java/Cell.java
  src/main/java/Stone.java
  src/test/java/CellTests.java
  src/test/java/StoneTests.java
Labels: enhancement

#18 10 board class
  src/main/java/Board.java
  src/main/java/Cell.java
  src/main/java/exceptions/InvalidBoardSizeException.java
  src/test/java/BoardTests.java
  src/test/java/CellTests.java
Labels: enhancement

#27 Implemented position ordering
  src/main/java/Position.java
  src/test/java/PositionTests.java
Labels: documentation, enhancement

#30 First design of the Game and Player class (with no tests)
  src/main/java/Board.java
  src/main/java/Game.java
  src/main/java/Player.java
Labels: enhancement

#31 Software design enhancement of Game class and Player class
  src/main/java/Game.java
  src/main/java/Move.java
  src/main/java/Player.java
  src/main/java/UserInput.java
  src/test/java/PlayerTests.java
Labels: enhancement

#35 Added logger class
  src/main/java/MainLogger.java
Labels: enhancement

#36 Removed BoardAnalyzer
  src/main/java/Board.java
  src/main/java/Game.java
  src/test/java/BoardTests.java
  src/test/java/CellTests.java
Labels: duplicate, enhancement

#39 38-board-testing
  build.gradle
  settings.gradle
  src/main/java/Board.java
  src/test/java/BoardTests.java
Labels: enhancement

#50 Added tests for `Board` `toString` method
  src/main/java/Board.java
  src/main/java/Game.java
  src/test/java/BoardTests.java
Labels: enhancement

#48 46 final score
  src/main/java/FreedomLine.java
  src/main/java/FreedomPointsCounter.java
  src/main/java/Game.java
  src/main/java/Player.java
  src/main/java/Stone.java
  src/test/java/FreedomLineTests.java
  src/test/java/FreedomPointsCounterTests.java
  src/test/java/StoneTests.java
Labels: enhancement

#54 52 iterator refactor
  src/main/java/FreedomPointsCounter.java
  src/main/java/Position.java
  src/test/java/BoardTests.java
  src/test/java/FreedomPointsCounterTests.java
Labels: bug, documentation, enhancement

#55 37 position as argument
  src/main/java/Board.java
  src/main/java/FreedomPointsCounter.java
  src/main/java/Position.java
  src/main/java/TextInput.java
  src/test/java/BoardTests.java
  src/test/java/FreedomLineTests.java
  src/test/java/FreedomPointsCounterTests.java
  src/test/java/PositionTests.java
Labels: enhancement

#57 Did some refactoring, organized into packages
  class_diagram.drawio
  src/main/java/Cell.java
  src/main/java/Main.java
  src/main/java/Move.java
  src/main/java/it/units/sdm/project/Main.java
  src/main/java/it/units/sdm/project/Player.java
  src/main/java/it/units/sdm/project/Position.java
  src/main/java/it/units/sdm/project/Stone.java
  src/main/java/it/units/sdm/project/TextInput.java
  src/main/java/it/units/sdm/project/core/FreedomGame.java
  src/main/java/it/units/sdm/project/core/FreedomLine.java
  src/main/java/it/units/sdm/project/core/FreedomPointsCounter.java
  src/main/java/it/units/sdm/project/core/MapBoard.java
  src/main/java/it/units/sdm/project/exceptions/InvalidBoardSizeException.java
  src/main/java/it/units/sdm/project/exceptions/InvalidPositionException.java
  src/main/java/it/units/sdm/project/interfaces/Board.java
  src/main/java/it/units/sdm/project/interfaces/Game.java
  src/main/java/it/units/sdm/project/interfaces/UserInput.java
  src/main/java/it/units/sdm/project/utils/MainLogger.java
  src/test/java/CellTests.java
  src/test/java/FreedomLineTests.java
  src/test/java/FreedomPointsCounterTests.java
  src/test/java/MapBoardTests.java
  src/test/java/PlayerTests.java
  src/test/java/PositionTests.java
  src/test/java/StoneTests.java
Labels: enhancement
